### ISSUE TITLE
A lot errors on Win7 X64 enterprise

### ISSUE THREAD

**Issue by zengxingdong** [winnfsd/winnfsd#30] opened 2016-08-24 12:05 UTC
client fails to mount the second folder.  winnfsd is lastest version 2.2.0. it seems always got a wrong path.

for example;
 the mount point is "/home"
nfs demon get wrong path "/h:ome".

OS: win7 x64 enterprise.

**Comment by zengxingdong** [comment] 2016-08-24 12:08
and also there are lots others bugs:

if i write the path as "c:\test /home/"

then mount it on linux with "/home"

winnfsd will crash.  or make the path like "c:\test /home", and write mount path on linux with "/home/"

winnfsd also crashed.........

**Comment by zengxingdong** [comment] 2016-08-24 12:29
another error:

cannot copy folder from linux to windows:

[20:25:30] NFS LOOKUP \\?\c:\Users\exingze\Desktop\IPW_AutoInstall  OK
[20:25:30] NFS ACCESS \\?\c:\Users\exingze\Desktop\IPW_AutoInstall  OK
[20:25:30] NFS LOOKUP \\?\c:\Users\exingze\Desktop\IPW_AutoInstall\log  OK
[20:25:30] NFS ACCESS \\?\c:\Users\exingze\Desktop\IPW_AutoInstall\log  OK
[20:25:30] NFS LOOKUP \\?\c:\Users\exingze\Desktop\IPW_AutoInstall\log\install.log  OK
[20:25:30] NFS GETATTR \\?\c:\Users\exingze\Desktop\IPW_AutoInstall\log\install.log  OK
[20:25:30] NFS ACCESS \\?\c:\Users\exingze\Desktop\IPW_AutoInstall\log\install.log  OK
[20:25:30] NFS SETATTR \\?\c:\Users\exingze\Desktop\IPW_AutoInstall\log\install.log  OK

it stops here "SETATTR". try many times and same error.

**Comment by marcharding** [comment] 2016-08-25 06:19
https://github.com/winnfsd/winnfsd/issues/30#issue-172934099 and https://github.com/winnfsd/winnfsd/issues/30#issuecomment-242040247: 
While i can't reproduce your problems, try again with this new [WinNFSd.zip](https://github.com/winnfsd/winnfsd/files/435753/WinNFSd.zip).

https://github.com/winnfsd/winnfsd/issues/30#issuecomment-242045158
I know about this, but have not yet figured out what exactly happens. Try mounting with TCP instead of UDP, e.g. `mount -t nfs ip:/share /share -o nolock,vers=3,tcp`

**Comment by zengxingdong** [comment] 2016-08-27 19:20
i think you have done that updated version. thanks to your effort.
but the problem is the issue is same with before even though i have used the sw given by you.

error log:
MOUNT Path C:\Users\exingze\Desktop  with path alias  /home already known
Path C:\Users\exingze\Documents\tftproot  with path alias  /exports already known
MNT from 20.0.0.6
Final local requested path: \\?\C:\Users\exingze\Documents\tftproot

PORTMAP GETPORT 100003 2049
[03:15:37] NFS NULL OK
[03:15:37] NFS FSINFO \\?\C:\Users\exingze\Documents\tftproot  OK
[03:15:37] NFS PATHCONF \\?\C:\Users\exingze\Documents\tftproot  OK
[03:15:37] NFS FSINFO \\?\C:\Users\exingze\Documents\tftproot  OK
PORTMAP GETPORT 100003 2049
[03:15:37] NFS NULL OK
PORTMAP GETPORT 100005 1058
MOUNT NULL
MOUNT NULL
MOUNT Path C:\Users\exingze\Desktop  with path alias  /home already known
Path C:\Users\exingze\Documents\tftproot  with path alias  /exports already known
MNT from 20.0.0.6
Final local requested path: \\?\C:\Users\exingze\Desktoprts

[03:15:37] NFS FSINFO \\?\C:\Users\exingze\Desktoprts  NOENT
[03:15:37] NFS FSINFO \\?\C:\Users\exingze\Desktoprts  NOENT

see above log: the right path should be "C:\Users\exingze\Desktop" instead of "C:\Users\exingze\Desktoprts".

**Comment by marcharding** [comment] 2016-08-27 20:54
I think i know whats wrong, can you paste you mount command, e.g. `mount -t nfs ip:/export `? i just need to know which path you want to mount.

**Comment by marcharding** [comment] 2016-08-28 00:00
Ok, i got it, try again with this file: [WinNFSd.zip](https://github.com/winnfsd/winnfsd/files/440907/WinNFSd.zip)

**Comment by zengxingdong** [comment] 2016-08-28 06:15
@marcharding thanks, test again, both mout path errors have been fixed successfully. this test is ok on my platform at least.

but for the third issue, it is still there. i have tried both UDP and TCP, both failure.
log is same as before:

`[14:03:55] NFS FSINFO \\?\C:\Users\exingze\Downloads  OK
[14:03:55] NFS PATHCONF \\?\C:\Users\exingze\Downloads  OK
[14:03:55] NFS FSINFO \\?\C:\Users\exingze\Downloads  OK
[14:06:11] NFS GETATTR \\?\C:\Users\exingze\Downloads  OK
[14:06:11] NFS GETATTR \\?\C:\Users\exingze\Desktop  OK
[14:06:11] NFS GETATTR \\?\C:\Users\exingze\Documents\tftproot  OK
[14:06:22] NFS ACCESS \\?\C:\Users\exingze\Downloads  OK
[14:06:22] NFS LOOKUP \\?\C:\Users\exingze\Downloads\IPW_AutoInstall  NOENT
[14:06:22] NFS MKDIR \\?\C:\Users\exingze\Downloads\IPW_AutoInstall  OK
[14:06:22] NFS ACCESS \\?\C:\Users\exingze\Downloads  OK
[14:06:22] NFS ACCESS \\?\C:\Users\exingze\Downloads\IPW_AutoInstall  OK
[14:06:22] NFS MKDIR \\?\C:\Users\exingze\Downloads\IPW_AutoInstall\log  OK
[14:06:22] NFS ACCESS \\?\C:\Users\exingze\Downloads\IPW_AutoInstall\log  OK
[14:06:22] NFS CREATE \\?\C:\Users\exingze\Downloads\IPW_AutoInstall\log\install.log  OK
[14:06:22] NFS SETATTR \\?\C:\Users\exingze\Downloads\IPW_AutoInstall\log\install.log  OK`

in server's log, it shows server stopped at "set attribute". in client, it hungs up. i had to reboot server each time..........

besides above issue, i also have another suggestion about winnfsd can run as a windows service in backround??? i think this should be easy, anyway, this just is a suggestion.

hopefully winnfsd can support NLM function, but......because i have no time to test NLM now....most of NFS servers don't support NLM...

thanks again.

**Comment by marcharding** [comment] 2016-08-30 10:56
I can reproduce the hang, but only with UDP, TCP works fine.

As for NLM: Probably will **not** be implemented any time soon.

**Comment by marcharding** [comment] 2016-10-06 21:14
I'm closing this since the path issue you had in the beginng is fixed in 2.3.0.  Thanks for helping me tracking it down!

Feel free to open a new issue for the "hanging" error. 

As for NLM: As stated before this will probably not be implemented any time soon, sorry.

**Closed by marcharding** 2016-10-06 21:14 UTC
