### ISSUE TITLE
Errors when accessing files unless I touch them first

### ISSUE THREAD

**Issue by 4ver** [winnfsd/winnfsd#12] opened 2015-12-05 18:55 UTC
In my projects I run build tools (nodejs/gulp) in a vm (using vagrant). When I first run `gulp` I get errors trying to read/write certain files. If I run `find . -exec touch {} \;` in the projects directory before running the build process it works fine.

Anyone have any ideas or have had similar issues?

Thanks,
Donal.

**Comment by philr** [comment] 2016-03-30 13:23
I had a similar problem with a Ruby on Rails server process failing to start in a Vagrant vm. Rails was calling `mkdir` on the `tmp/pids` directory (which already existed) and then trying to create a file in that directory. The file creation would fail, despite the directory existing. If I ran `ls -l tmp/pids` before starting Rails, it would successfully create the file.

The problem I encountered was caused by a bug handling error codes in the implementation of the mkdir operation. I've opened PR #17 with a fix.

**Comment by marcharding** [comment] 2016-06-04 12:18
I do not have this problem, however the fix from @philr is merged in the latest alpha, please take a look 

https://github.com/winnfsd/winnfsd/releases/tag/3.0.0ALPHA

**Comment by marcharding** [comment] 2016-06-23 22:23
The latest release (2.1.0) has the fix from @philr included.

Please test if the issue persists.

**Comment by marcharding** [comment] 2016-08-07 19:12
I'm closing this due to no activity and because the problem seems to be fixed already.

**Closed by marcharding** 2016-08-07 19:12 UTC
