### ISSUE TITLE
Windows 7 "mount.nfs: system call failed"

### ISSUE THREAD

**Issue by kevinquillen** [winnfsd/winnfsd#5] opened 2015-08-05 13:48 UTC
I understand this is the new repository, but there are issues I would like to read again. Namely the one about 'mount.nfs: system call failed' - because I am getting that exact error on another machine.

**Comment by yannschepens** [comment] 2015-08-05 14:00
You can not access this page ? 
: https://bitbucket.org/jankowfsky/winnfsd/issues?status=new&status=open

**Comment by kevinquillen** [comment] 2015-08-05 14:00
I get Access Denied, even when logged in.

**Comment by GM-Alex** [comment] 2015-08-05 14:07
Hey I set the issue tracker to private prevent that some creates new issues there. We have to port them to github.

**Comment by yannschepens** [comment] 2015-08-05 14:10
The only ones I founded relative to are there : 

Can't export whole drive/partition :
It's not possible to mount exported disk/partition.
Server runs normally, but mount returns:
# mount 192.168.2.1:/www /w
mount.nfs: mount system call failed
Steps to reproduce:
WinNFSd.exe w:\ /www
mount [ip]:/www /mnt/nfs
I'm using Windows 7 Home Edition.

**Comment by yannschepens** [comment] 2015-08-05 14:11
And this one : 

I can't actually get a share to mount, and I was just curious if you've seen this error before...
Windows:
Win7 Prox64 C:\Users\markc.vagrant.d\gems\gems\vagrant-winnfsd-1.0.3\bin>winnfsd.exe C:\test ===================================================== WinNFSd v2.0 Network File System server for Windows Copyright (C) 2005 Ming-Yang Kao Edited in 2011 by ZeWaren Edited in 2013 by Alexander Schneider (Jankowfsky AG) ===================================================== Mounting 1 paths Path #1 is: C:\test, path alias is: /C/test Portmap daemon started NFS daemon started Mount daemon started Local IP = 172.22.0.115 Type 'help' to see help
NFS NULL OK NFS GETATTR (null) STALE
Linux:
Ubuntu 13.04 x64 vagrant@vagrant-devhost:~$ sudo mount -t nfs 172.22.0.115:/test /mnt/nfs/ mount.nfs: mount system call failed

**Comment by yannschepens** [comment] 2015-08-05 14:12
The first one is resolved and for the second one, the response was : 

The mount command should look like the following
sudo mount -o 'vers=3,nolock,udp' 172.22.0.115:/C/test /var/test

**Comment by yannschepens** [comment] 2015-08-05 14:12
@kevinquillen tell me if these information are ok for you

**Comment by kevinquillen** [comment] 2015-08-05 14:12
That would be it (mount call failed). Trying to uncover this mysterious error.

I had the dev downgrade to vbox 4.3.30 on Windows (I have not yet tried 5). Deleted the .vagrant folder in the directory, and vagrant up. The console seemed to ignore Virtualbox completely then, and was saying "verifying hyper v is enabled" as a provider. Have never seen that one before.

**Comment by magnetik** [comment] 2015-08-11 14:59
Got the same with Virtualbox 5.0 and Windows 7

**Comment by yannschepens** [comment] 2015-08-26 07:35
Sometimes, you have just to halt the VM and kill winnfsd process.

Currently, I have not tried with virtualbox 5.0.

**Comment by marcharding** [comment] 2016-06-04 12:17
Can you try again with the latest alpha please?

https://github.com/winnfsd/winnfsd/releases/tag/3.0.0ALPHA

**Comment by marcharding** [comment] 2016-08-25 16:53
Do you still have problems with this? Otherwise i'll close this issue.

**Comment by marcharding** [comment] 2016-09-29 07:43
Closing this due to no response

I also think this is probably fixed in one of the more current releases as this issue is more than a year old.

**Closed by marcharding** 2016-09-29 07:43 UTC

**Comment by alanzhucn** [comment] 2019-08-28 09:46
Hi, @kevinquillen @marcharding @magnetik @yannschepens 
I meet the same problem today. And following @yannschepens  's advice, I include the option 'vers=3,nolock,udp' then it works. 

sudo mount -o 'vers=3,nolock,udp' 172.22.0.115:/C/test /var/test
